# Generated by Django 5.2.5 on 2025-09-09 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
