# Generated by Django 5.2.5 on 2025-09-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_review'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='technicians_technic_29982b_idx',
            old_name='technician_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='technicians_reviewe_2894a4_idx',
            old_name='reviewer_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='technicians_created_bf1f5a_idx',
            old_name='created_at_idx',
        ),
    ]
