# Generated by Django 5.2.5 on 2025-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0004_rename_technician_idx_technicians_technic_29982b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='criminal_record',
            field=models.FileField(blank=True, null=True, upload_to='criminal_records/'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='criminal_record_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='criminal_record_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='national_id_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_docs/'),
        ),
    ]
