# Generated by Django 5.2.5 on 2025-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_provider_tx_id_payment_tx_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
